/**
 * 阅米数据库初始化脚本
 * Author:  eglic
 * Created: 2018-3-14
 */
DROP TABLE IF EXISTS `task_sign`;
CREATE TABLE `task_sign` (
	`id` 			INT UNSIGNED 			NOT NULL AUTO_INCREMENT					COMMENT '记录ID',
	`user_id`		INT UNSIGNED			NOT NULL								COMMENT '用户ID',
	`month_id`		INT UNSIGNED			NOT NULL								COMMENT '月份ID：YYYYMM',
	`day_1`			TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_2`			TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_3`			TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_4`			TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_5`			TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_6`			TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_7`			TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_8`			TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_9`			TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_10`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_11`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_12`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_13`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_14`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_15`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_16`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_17`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_18`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_19`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_20`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_21`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_22`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_23`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_24`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_25`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_26`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_27`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_28`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_29`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_30`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',
	`day_31`		TINYINT UNSIGNED		NOT NULL DEFAULT 0						COMMENT '1号',

	PRIMARY KEY (`id`),
	KEY `user_id` (`user_id`),
	KEY `month_id` (`month_id`),
	UNIQUE KEY `user_month_id` (`user_id`,`month_id`)
) Engine=InnoDB
  DEFAULT CHARACTER SET=utf8 
  COLLATE=utf8_general_ci
  COMMENT='签到任务';