/**
 * 素材系统
 */
DROP TABLE IF EXISTS `release`;
DROP TABLE IF EXISTS `contract_template`;

ALTER TABLE `tally_coin` CHANGE COLUMN `order_id` `order_id` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '订单ID';
ALTER TABLE `tally_money` CHANGE COLUMN `order_id` `order_id` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '订单ID';
ALTER TABLE `tally_profit` CHANGE COLUMN `order_id` `order_id` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '订单ID';
ALTER TABLE `tally_recruit` CHANGE COLUMN `order_id` `order_id` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '订单ID';
ALTER TABLE `vip_buff` CHANGE COLUMN `order_id` `order_id` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '订单ID';
ALTER TABLE `cheif_buff` CHANGE COLUMN `order_id` `order_id` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '订单ID';
ALTER TABLE `director_buff` CHANGE COLUMN `order_id` `order_id` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '订单ID';
ALTER TABLE `user_withdraw` CHANGE COLUMN `order_id` `order_id` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '订单ID';
ALTER TABLE `user_charge` CHANGE COLUMN `order_id` `order_id` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '订单ID';
ALTER TABLE `consult` CHANGE COLUMN `order_id` `order_id` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '订单ID';


ALTER TABLE `user_material` DROP COLUMN `file_name`;
ALTER TABLE `user_material` CHANGE COLUMN `create_time` `create_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间 @TIMESTAMP-CREATE';
ALTER TABLE `user_material` CHANGE COLUMN `audit_time` `audit_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '审核时间';

ALTER TABLE `user_bank` CHANGE COLUMN `create_time` `create_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间 @TIMESTAMP-CREATE';
ALTER TABLE `user_bank` CHANGE COLUMN `audit_time` `audit_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '审核时间';

ALTER TABLE `user_ticket` CHANGE COLUMN `create_time` `create_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间 @TIMESTAMP-CREATE';
ALTER TABLE `user_ticket` CHANGE COLUMN `use_time` `use_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用时间';

ALTER TABLE `user_charge` CHANGE COLUMN `create_time` `create_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间 @TIMESTAMP-CREATE';
ALTER TABLE `user_charge` CHANGE COLUMN `accept_time` `accept_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '支付时间';

ALTER TABLE `user_address` CHANGE COLUMN `create_time` `create_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间 @TIMESTAMP-CREATE';
ALTER TABLE `supplier` CHANGE COLUMN `create_time` `create_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间 @TIMESTAMP-CREATE';
ALTER TABLE `tally_coin` CHANGE COLUMN `create_time` `create_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间 @TIMESTAMP-CREATE';
ALTER TABLE `tally_money` CHANGE COLUMN `create_time` `create_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间 @TIMESTAMP-CREATE';
ALTER TABLE `tally_profit` CHANGE COLUMN `create_time` `create_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间 @TIMESTAMP-CREATE';
ALTER TABLE `tally_recruit` CHANGE COLUMN `create_time` `create_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间 @TIMESTAMP-CREATE';
ALTER TABLE `rbac_admin` CHANGE COLUMN `create_time` `create_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间 @TIMESTAMP-CREATE';
ALTER TABLE `director` CHANGE COLUMN `create_time` `create_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间 @TIMESTAMP-CREATE';
ALTER TABLE `director` CHANGE COLUMN `update_time` `update_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间';
ALTER TABLE `cheif` CHANGE COLUMN `create_time` `create_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间 @TIMESTAMP-CREATE';
ALTER TABLE `cheif` CHANGE COLUMN `update_time` `update_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间';

ALTER TABLE `device` CHANGE COLUMN `create_time` `create_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间 @TIMESTAMP-CREATE';
ALTER TABLE `device` CHANGE COLUMN `update_time` `update_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间';

ALTER TABLE `sms` CHANGE COLUMN `create_time` `create_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间 @TIMESTAMP-CREATE';
ALTER TABLE `sms` CHANGE COLUMN `expire_time` `expire_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '过期时间';

