ALTER TABLE `vip_card` CHANGE COLUMN `serial` `serial` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '卡号';
ALTER TABLE `cheif_card` CHANGE COLUMN `serial` `serial` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '卡号';
